<?php

namespace App\Console\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

#[Signature('docs:appendix')]
#[Description('Concatenate docs/*.md guides into .scribe/append.md so scribe:generate renders them after the endpoints')]
class BuildDocsAppendix extends Command
{
    /**
     * Build the Scribe appendix from the workflow guides.
     *
     * Why this exists: Scribe 5.x has no `pages` config — it renders
     * `.scribe/intro.md`, the endpoints, then `.scribe/append.md` (when
     * present). So the guides in docs/ reach the HTML docs through this
     * file. Run it before scribe:generate (or add to CI); it is
     * deterministic — same guides in, byte-identical file out.
     */
    public function handle(): int
    {
        $guides = File::glob(base_path('docs/*.md'));

        if ($guides === false || $guides === []) {
            $this->error('No guides found in docs/.');

            return self::FAILURE;
        }

        sort($guides);

        $parts = [
            '<!-- GENERATED by `php artisan docs:appendix` from docs/*.md — do not edit by hand. -->',
        ];

        foreach ($guides as $guide) {
            $parts[] = File::get($guide);
        }

        File::put(base_path('.scribe/append.md'), implode("\n\n---\n\n", $parts)."\n");

        $this->info('Appendix built from '.count($guides).' guides.');

        return self::SUCCESS;
    }
}
